### ISSUE TITLE
Collect list of online resources that could be useful for learning about remote collaboration

### ISSUE THREAD

**Issue by dfm** [tess-science/online#11]
Suggested by @grd349 in #3 

- [x] Tutorials about Git and GitHub

Other ideas?

**Comment by grd349** [comment]
Unit tests?  Pytest?

**Comment by dfm** [comment]
I asked for suggestions [on Twitter](https://twitter.com/exoplaneteer/status/1298310760884572160) and have been getting some good recommendations. So far:

- https://about.gitlab.com/company/culture/all-remote/guide/
- https://handbook.tts.gsa.gov/
- https://software-carpentry.org/lessons/index.html and, especially, https://swcarpentry.github.io/git-novice/
- https://docs.github.com/en/github
- https://teletype.atom.io/

**Comment by dfm** [comment]
Another tool recommendation: https://glitch.com/create

**Comment by grd349** [comment]
What do we reckon here - can we close or should we seriously consider unit tests?

Was pair coding going to be a thing?

**Comment by dfm** [comment]
I'm happy to close! I think that @christinahedges is thinking about doing a tutorial about teletype in atom, but I think we're in good shape as far as this issue goes. Thanks @grd349!!
