### ISSUE TITLE
How do participants contact the SOC?

### ISSUE THREAD

**Issue by benmontet** [tess-science/online#12]
Beyond CoC issues, if someone wants to bring up something for conversation with the SOC, what should we identify as the preferred method to do that? Sliding into our DMs? An "ask-the-soc" slack channel? A breakout room? Or something else entirely?

**Comment by dfm** [comment]
There are now a `@organizers` group and a `@facilitators` group on Slack that can be tagged in conversations. Unfortunately it looks like it's not possible to DM a group :/ so I can create an email list or something.

**Comment by dfm** [comment]
OK - I came up with a possible solution, but it'll need to be documented. You can now go to the `#questions` channel and click the shortcuts button:

<img width="373" alt="Screen Shot 2020-08-25 at 10 05 56 AM" src="https://user-images.githubusercontent.com/350282/91184396-95d08e00-e6ba-11ea-9578-9517c7f5294b.png">

and then select "Contact the organizers" or "Contact the facilitators":

<img width="488" alt="Screen Shot 2020-08-25 at 10 06 27 AM" src="https://user-images.githubusercontent.com/350282/91184480-af71d580-e6ba-11ea-827a-34b954fa01a5.png">

Which will let folks send an (optionally anonymous) message to the private `#organizers-contact` or `#facilitators-contact` channels. Try it out!

**Comment by grd349** [comment]
I just sent a message to the facilitators but rather than remaining anonymous I was able to send it as Ben.  Is this a major concern?

**Comment by grd349** [comment]
Ignore closed issue - stupid above average sized fingers

**Comment by grd349** [comment]
> I just sent a message to the facilitators but rather than remaining anonymous I was able to send it as Ben. Is this a major concern?

Looks like the plan is to have two shortcuts - one anonymous and the other including username.

**Comment by dfm** [comment]
Yes - I think it'll work now, but there's a chance that the text isn't 100% clear. So any feedback is welcome!

**Comment by benmontet** [comment]
I think this is really great and I put words about it into the handbook. I'm happy for this to be closed if everyone is happy!

**Comment by dfm** [comment]
I think the description in the handbook is excellent - thanks @benmontet!
