### ISSUE TITLE
Make a few demo tutorials: Yotribe and GitHub Projects

### ISSUE THREAD

**Issue by dfm** [tess-science/online#8]
I think it would be awesome to have some tutorials come out of this, but I'm not sure how much we want to organize that ourselves.

I think that the best option would be to have a #tutorials channel on Slack where people can ask for or pitch tutorials. Then we could let people self organize and run tutorials in the usual ad-hoc way via zoom, google meet, or pre-recorded video. If using Zoom or Google meet, perhaps we could encourage the presenter(s) to record the meeting and share it on Slack after?

Anyone want to try an experiment? Some ideas:

@grd349: GitHub projects?
@christinahedges: Remote pair coding via atom/vscode?

**Comment by dfm** [comment]
There was also a request for a tutorial on GitHub more generally.

**Comment by dfm** [comment]
Another idea: Google Colab.

**Comment by dfm** [comment]
Also: google meet recordings (and meetings more generally) support automatic closed captioning so we should probably encourage that. Similarly, you can get automatic closed captioning using youtube, I think.

**Comment by dfm** [comment]
From @grd349 in #3:

> Does it make sense to have a slack channel for each 'tutorial' video to collect all questions?

That sounds like a good plan to me.

**Comment by grd349** [comment]
Do we need a Yotribe tutorial?  There are probably plenty of 3rd party resources.  On the other hand, it might be an opportunity to set some social norms (feel free to join any group, just drop in and say hi, be welcoming, ...).

**Comment by dfm** [comment]
+1 for Yotribe tutorial. Anyone up to join for a group call one day this week to record one? I think it can just be short!

**Comment by benmontet** [comment]
+1 again for Yotribe tutorial. It will also give us experience creating tutorials! Happy to be involved or not depending on what time zone works for others.

**Comment by grd349** [comment]
Do we have any restrictions on where we host video from recorded tutorials?  My gut said YouTube but that might cause access issues.

**Comment by dfm** [comment]
I think YouTube would be my choice too. I wasn't able to find any platforms that had no access restrictions.
